server {
	listen 		8001;
	host  127.0.0.1 ;
	server_name	test;
	error_page 404 errors/404.html;
	client_max_body_size 1024;
	index index.html;
	root ./;			o

	location post/ {
	autoindex on;
	allow_methods  GET DELETE;
	#index conf_del.html;
	#alias tmp;
	# return    return.html;
	}

	location tmp/ {
	autoindex on;
	allow_methods  GET;
	#index conf_del.html;
	#alias tmp;
	# return    return.html;
	}

	location loin/ {				o
	autoindex on;					|||
	allow_methods POST GET;
	#index index_post.html;
	#alias loin/TresLoin/TresTresLoin;
	#return    return.html;
	}

	location loin2/ {				o
	autoindex on;					|||
	allow_methods GET;
	#index index_post.html;
	alias loin/;
	#return    zebi;
	}

	# location post/ {				o
	# autoindex on;					|||
	# allow_methods POST 	GET;
	# index index_post.html;	
	# # return    return.html;
	# }

	location cgi-bin/ {
	allow_methods GET POST;
	cgi_path /usr/bin/python3; |||
	cgi_ext .py;
	}
}

merge || 

on fait un file post, avec du coup post pr file comme avant sauf que si on va sur la page post_cgi, 