server {
	listen 		8001;				o
	host  127.0.0.1;
	server_name	test;				o|||
	# error_page 404 error/404.html;
	# client_max_body_size 1024;
	root /home/armitite/Cursus/19_webserver;			o
	# index index.html;

	location tours/ {				o
	autoindex on;					|||
	allow_methods POST 	GET;
	index index_tours.html;
	# return    abc/index1.html;
	}

	location post/ {				o
	autoindex off;					|||
	allow_methods POST 	GET;
	index index_post.html;
	return    return.html;
	}

	# location /cgi-bin {
	# root ./;
	# cgi_path /usr/bin/python3 /bin/bash; |||
	# cgi_ext .py .js .sh;
	# }
}
