server {
	listen 		8001;				o
	host  127.0.0.1;
	server_name	test;				o|||
	error_page 404 errors/404.html;
	# client_max_body_size 1024;
	index index.html;
	root /home/najeuneh/cursus/19_webserver;			o

	# location tours/ {				o
	# autoindex on;					|||
	# allow_methods POST 	GET;
	# index index_tours.html;
	# # return    abc/index1.html;
	# }

	location post/ {				o
	autoindex on;					|||
	allow_methods POST 	GET;
	#index index_post.html;
	#alias tmp;
	# return    return.html;
	}

	location get_cgi/ {
	autoindex on;
	allow_methods POST GET;
	alias cgi-bin/;
	#index      page2.html;
	# return     random_wikipedia.html;
	}

	# location post/ {				o
	# autoindex on;					|||
	# allow_methods POST 	GET;
	# index index_post.html;	
	# # return    return.html;
	# }

	location cgi-bin/ {
	allow_methods GET POST;
	root ./;
	cgi_path /bin/python3; |||
	cgi_ext .py .sh;
	script	  cgi-bin/script;
	}
}

merge || 

on fait un file post, avec du coup post pr file comme avant sauf que si on va sur la page post_cgi, 